DOMAIN = "eqiva_keyble"
PLATFORMS = ["lock", "sensor", "text"]

CONF_ADDRESS = "address"
CONF_USER_ID = "user_id"
CONF_USER_KEY = "user_key"
CONF_KEY_CARD = "key_card"
CONF_NAME = "name"
CONF_SETUP_METHOD = "setup_method"
CONF_POLL_INTERVAL = "poll_interval"
CONF_CONNECTION_MODE = "connection_mode"
CONF_KNX_ENABLED = "knx_enabled"
CONF_KNX_LOCK_ADDRESS = "knx_lock_address"
CONF_KNX_UNLOCK_ADDRESS = "knx_unlock_address"
CONF_KNX_OPEN_ADDRESS = "knx_open_address"
CONF_KNX_LOCKED_STATE_ADDRESS = "knx_locked_state_address"
CONF_KNX_BATTERY_LOW_ADDRESS = "knx_battery_low_address"
CONF_KNX_AVAILABLE_ADDRESS = "knx_available_address"

SETUP_KEY_CARD = "key_card"
SETUP_CREDENTIALS = "credentials"

CONNECTION_MODE_POLLING = "polling"
CONNECTION_MODE_LIVE = "live"

DEFAULT_NAME = "Eqiva Türschloss"
DEFAULT_POLL_INTERVAL = 10
MIN_POLL_INTERVAL = 1
MAX_POLL_INTERVAL = 60
DEFAULT_CONNECTION_MODE = CONNECTION_MODE_POLLING
DEFAULT_KNX_ENABLED = False

KNX_ADDRESS_OPTIONS = (
    CONF_KNX_LOCK_ADDRESS,
    CONF_KNX_UNLOCK_ADDRESS,
    CONF_KNX_OPEN_ADDRESS,
    CONF_KNX_LOCKED_STATE_ADDRESS,
    CONF_KNX_BATTERY_LOW_ADDRESS,
    CONF_KNX_AVAILABLE_ADDRESS,
)

SERVICE_UUID = "58e06900-15d8-11e6-b737-0002a5d5c51b"
SEND_CHARACTERISTIC_UUID = "3141dd40-15db-11e6-a24b-0002a5d5c51b"
RECEIVE_CHARACTERISTIC_UUID = "359d4820-15db-11e6-82bd-0002a5d5c51b"
